docker_name: eduix/confluence
script:
  - "echo \"Dummy job for starting branch specific ones\""
git:
  branches:
    - master
    - stable
    - staging
  extensions:
    checkout_local_branch: true
clean_workspace: true
downstream:
  - docker-confluence-master
  - docker-confluence-staging
  - docker-confluence-stable

extra_jobs:
    - name: docker-confluence-daily
      builders:
        - docker
      git:
        branch: master
      triggers:
        github_push: false
        cron: "@daily"
    - name: docker-confluence-master
      builders:
        - docker
      docker_tags:
        - "master"
      git:
        branch: master
    - name: docker-confluence-staging
      builders:
        - docker
      docker_tags:
        - "staging"
      git:
        branch: staging
    - name: docker-confluence-stable
      builders:
        - docker
      docker_tags:
        - "stable"
      git:
        branch: stable
